tomatoman2/freemarket_sample_73h

README.md
READMEファイルへのDB定義の記述
READMEへDB定義を記述することで全体像を理解できるようにする
=> READMEファイルへのDB定義記述

README.md, app/models/product.rb, app/models/product_image.rb, db/migrate/20200423115651_create_products.rb, db/migrate/20200423115733_create_product_images.rb
product,product_imageのマイグレーション及びモデルの追記
product,product_imageテーブルを作成するため
=> product,product_imageのマイグレーション及びモデルの追記

app/models/code.rb, app/models/order.rb, db/migrate/20200423115950_create_codes.rb, db/migrate/20200423120014_create_orders.rb
#What
Oder/Codeテーブルの、マイグレーションファイルとモデルを記述。
#Why
商品購入機能、名称のデータ搭載に必要となる為。
=> Fix-oder/Fix-code

app/models/user.rb, db/migrate/20200423100616_devise_create_users.rb
＃What
userモデルとマイグレーションファイルの編集
＃Why
データベースの準備
=> user モデル　マイグレーション作成

app/models/address.rb, app/models/credit_card.rb, db/migrate/20200423115504_create_addresses.rb, db/migrate/20200423115616_create_credit_cards.rb
address,credit_cardマイグレーション及びモデルの追記
address,credit_cardテーブルを作成するため
=> マイグレーションファイル、モデル編集

app/models/brand.rb, app/models/category.rb, db/migrate/20200423115828_create_categories.rb, db/migrate/20200423115845_create_brands.rb
#WHAT
マイグレーションファイルの編集
#WHY
データベース設計に必要
=> migrate_file edit

app/models/comment.rb, app/models/like.rb, db/migrate/20200423115752_create_comments.rb, db/migrate/20200423115807_create_likes.rb
#WHAT
like&commentのカラム
#WHY
DB設計
=> like&comment

db/migrate/20200423115752_create_comments.rb, db/migrate/20200423115807_create_likes.rb
#WHAT
like&comment訂正
#WHY
間違い訂正
=> like&comment訂正

app/assets/stylesheets/_orders.scss, app/assets/stylesheets/application.scss, app/controllers/orders_controller.rb, app/views/layouts/_footer.html.haml, app/views/orders/new.html.haml, config/routes.rb
商品購入確認ページ(マークアップ)の作成
フリマアプリの商品購入の確認をするためのページ
=> 商品購入確認ページ実装

app/assets/stylesheets/_header.scss, app/assets/stylesheets/_home.scss, app/assets/stylesheets/_items-show.scss, app/models/product.rb, app/models/product_image.rb, app/uploaders/image_uploader.rb, app/views/home/index.html.haml, app/views/items/new.html.haml, app/views/items/show.html.haml, app/views/layouts/_footer.html.haml, app/views/layouts/_header.html.haml
assets/images下にある画像に、asset_pathを指定。
および、image_uploader.rbの作成・accepts_nested_attributes_forメソッド使用の処理。
本番環境・開発環境ともに、assets/imagesの画像を取り込めるようにする為。
=> Fix:アセットパイプラインの処理

config/routes.rb
devise/userのルーティングを修正。
deviseのコントローラーを継承しユーザーコントローラーの使用を可能とする為。
=> Fix:routes

app/controllers/users/registrations_controller.rb
ユーザーコントローラーの記述の修正。
ユーザー新規登録画面のビュー表示を本番環境にて確認する為。
=> Fix:ユーザーコントローラー

app/views/users/registrations/new.html.haml
ユーザーの新規登録画面のビューを修正。
本番環境でビューの確認をする為。
=> Fix:ユーザー新規登録画面

config/environments/production.rb
config.consider_all_requests_local       = true
を設定。
本番環境でもエラー文を表示させる為。
=> Fix:本番環境にてエラー表示する設定

app/models/user.rb, app/views/home/index.html.haml, app/views/users/registrations/new.html.haml
ホーム画面・ユーザー新規登録画面のビューを修正。
本番環境の表示が適うようにする為。
=> Fix:ホーム・ユーザー新規登録画面のビューを修正

app/assets/stylesheets/_footer.scss, app/assets/stylesheets/_home.scss
ホーム画面・フッターの画像の表示を修正。
本番環境において表示がされるようにする為。
=> Fix:本番環境における画像の表示

Gemfile, Gemfile.lock, app/models/product.rb
Gem fog-aws を導入。
および、orderとproductのアソシエーション修正。
本番環境の画像保存先をS3に設定する為。
=> Fix:本番環境画像保存の設定

config/deploy.rb, db/migrate/20200509133158_change_datatype_status_of_product.rb
productテーブルstatus:integer に変更するマイグレーションファイルを追加。
本番環境のproductテーブル のカラム：statusを文字列に変更する為。
=> change:マイグレーションファイルの修正

app/views/items/index.html.haml, app/views/layouts/_header.html.haml
商品一覧ページより、選択した商品の詳細ページにリンクするよう修正。
利用するユーザーが閲覧しやすいようにする為。
=> Fix:リンクを追加

app/controllers/items_controller.rb
本番環境でのテストのため、商品編集の例外処理を一時的に外す
本番環境でのテストのため、商品編集の例外処理を一時的に外す
=> 本番環境でのテストのため、商品編集の例外処理を一時的に外す

app/views/items/edit.html.haml
商品編集ページのform_with にmultipart true を追加
本番環境でのみ発生するproduct_imagesのupdate処理エラーへの解決案
=> 商品編集ページにmultipart true を追加

app/views/items/edit.html.haml
form_with にmultipart: trueを追加
本番環境での商品編集ページエラーへの対応
=> 商品編集ページ本番環境エラーへの対応

db/migrate/20200512081823_drop_credit_card.rb, db/migrate/20200512081919_create_credit_card.rb
クレジットカードテーブルをpayjpに合わせた形で再作成する
payjpを使用するため
=> クレジットカードテーブルの再作成

app/controllers/credit_card_controller.rb
クレジットカード登録の例外処理を外す。
本番環境でのエラーを確認する為。
=> Fix:クレジットカード登録に際し、本番環境でのエラーの確認する為

app/views/home/index.html.haml
=> 検証用のコードを記述

app/views/home/index.html.haml
本番環境用のテストコードを削除
本番環境での検証のために追記していたテストコードを削除
=> 本番環境用のテストコードを削除

app/views/credit_card/show.html.haml
クレジットカード削除画面の編集
クレジットカード削除画面を見やすくするため
=> クレジットカード削除画面変更
